### ISSUE TITLE
queries for LeftColumn, RightColumn

### ISSUE THREAD

**Issue by jkao1** [stuyspec/stuy-spec-api#68]
There are three articles I need in LeftColumn. None of them should be on the top 5 recommended articles on the HomePage, so their relative rankings are at least 6th. One of the articles must have an outquote.

In the RightColumn, I need two articles that are not already in LeftColumn or RecommendedArticles.

If it's easier for you, these two queries don't have to be separate.

**Comment by NicholasLYang** [comment]
Where are the outquotes coming from?

**Comment by jkao1** [comment]
Outquotes are a model that has `article_id`. "OutquoteArticle" means an article that has an outquote.
