### ISSUE TITLE
ID or Id? ID.

### ISSUE THREAD

**Issue by jkao1** [stuyspec/stuy-spec-api#70]
We've had it as `Id` for a while (e.g. `articleId`, `userId`). However, with the introduction of GraphQL, we should be consistent and change all uses of `Id` to `ID`.

**Comment by NicholasLYang** [comment]
Where's the inconsistency?

**Comment by jkao1** [comment]
Nevermind--this problem came from article_id being "camelized" into articleId on CFA. This problem does not exist in stuy-spec-api.
